### ISSUE TITLE
Invalid search query raises uncaught exception

### ISSUE THREAD

**Issue by gmr** [AWeber-Imbi/imbi#87]
When searching using `NOT links.sonarqube:https://sonarqube.aweber.io*` as the query, there's an uncaught exception. This should be caught and raised in the UI as an error:

```
ast.js:38 Uncaught KQLSyntaxError: Expected ")", AND, OR, whitespace but ":" found.
(NOT links.sonarqube:https://sonarqube.aweber.io*) AND NOT archived:true
--------------------------^
    at Qw (ast.js:38:13)
    at p (Projects.jsx:178:11)
    at onSubmit (Projects.jsx:258:13)
    at onSubmit (Filter.jsx:19:5)
    at Object.Ye (react-dom.production.min.js:52:317)
    at Xe (react-dom.production.min.js:52:471)
    at react-dom.production.min.js:53:35
    at Cr (react-dom.production.min.js:100:68)
    at wr (react-dom.production.min.js:101:380)
    ```

**Comment by gmr** [comment]
Is a dupe of #47
